version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    networks:
      - mlops-network

  prefect:
    image: prefecthq/prefect:2-latest
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200
    networks:
      - mlops-network

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mlflow
      - prefect
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge 